server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_booking_dbs?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: cse@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # In production this would be validate or none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# JWT Configuration
app:
  jwt:
    # This should be a base64 encoded string of at least 256 bits
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 864000000 # 1 day in milliseconds
